apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directus-plural.secretName" . }}
  labels:
{{ include "directus-plural.labels" . | indent 4 }}
stringData:
  key: {{ .Values.directus.key }}
  secret: {{ .Values.directus.secret }}
  {{- if .Values.directus.oidc.enabled }}}
  oidc-issuer: {{ .Values.directus.oidc.issuer }}
  oidc-client-id: {{ .Values.directus.oidc.clientId }}
  oidc-client-secret: {{ .Values.directus.oidc.clientSecret }}
  {{- end }}