cubes:
  - name: example
    sql_table: example
    data_source: default
    joins: []
    dimensions:
      - name: id
        sql: id
        type: string
        primary_key: true
      - name: product_id
        sql: product_id
        type: string
    measures:
      - name: count
        type: count
    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
