apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meilisearch-plural.secretName" . }}
  labels:
{{ include "meilisearch-plural.labels" . | indent 4 }}
stringData:
  MEILI_MASTER_KEY: {{ .Values.meilisearch.masterKey }}